# Generated by Django 5.2.13 on 2026-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('type', models.CharField(blank=True, max_length=9, null=True)),
                ('subtype', models.CharField(blank=True, max_length=256, null=True)),
                ('formula', models.CharField(max_length=256)),
                ('mw', models.CharField(blank=True, max_length=16, null=True)),
                ('mwsrc', models.CharField(blank=True, max_length=16, null=True)),
                ('inchikey', models.CharField(blank=True, max_length=27, null=True)),
                ('files', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('systems', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'substances',
                'managed': False,
            },
        ),
    ]
