# Generated by Django 5.2.13 on 2026-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trcid', models.CharField(blank=True, max_length=32, null=True)),
                ('abstract', models.CharField(blank=True, max_length=4096, null=True)),
                ('date', models.CharField(blank=True, max_length=16, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(max_length=128)),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
    ]
