# Generated by Django 5.2.13 on 2026-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('coden', models.CharField(blank=True, max_length=128, null=True)),
                ('issn', models.CharField(blank=True, max_length=9, null=True)),
                ('set', models.CharField(blank=True, max_length=8, null=True)),
                ('language', models.CharField(max_length=201)),
                ('abbrev', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('doiprefix', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'journals',
                'managed': False,
            },
        ),
    ]
