# Generated by Django 5.2.13 on 2026-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(blank=True, max_length=256, null=True)),
                ('chk', models.BooleanField(db_column='check')),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'keywords',
                'managed': False,
            },
        ),
    ]
