# Generated by Django 5.2.13 on 2026-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('composition', models.CharField(blank=True, max_length=19, null=True)),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('refcnt', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('setcnt', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'systems',
                'managed': False,
            },
        ),
    ]
