# Generated by Django 5.2.13 on 2026-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('authors', models.CharField(blank=True, max_length=2048, null=True)),
                ('aulist', models.CharField(blank=True, max_length=2048, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=12, null=True)),
                ('issue', models.CharField(blank=True, max_length=16, null=True)),
                ('startpage', models.CharField(blank=True, max_length=16, null=True)),
                ('endpage', models.CharField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('doi', models.CharField(max_length=256)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'references',
                'managed': False,
            },
        ),
    ]
